In [43]:
import pandas as pd
pd.read_csv ('data.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [2]:
import pandas as pd
pd.read_csv ('data.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'

In [3]:
import os
print(os.getcwd())

/Users/martarachwani

In [4]:
import pandas as pd
pd.read_csv('/Users/martarachwani/Desktop/data.csv')

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,18202,238813,J. Lundstram,19,https://cdn.sofifa.org/players/4/19/238813.png,England,https://cdn.sofifa.org/flags/14.png,47,65,Crewe Alexandra,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,18203,243165,N. Christoffersson,19,https://cdn.sofifa.org/players/4/19/243165.png,Sweden,https://cdn.sofifa.org/flags/46.png,47,63,Trelleborgs FF,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,18204,241638,B. Worman,16,https://cdn.sofifa.org/players/4/19/241638.png,England,https://cdn.sofifa.org/flags/14.png,47,67,Cambridge United,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,18205,246268,D. Walker-Rice,17,https://cdn.sofifa.org/players/4/19/246268.png,England,https://cdn.sofifa.org/flags/14.png,47,66,Tranmere Rovers,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/246269.png,England,https://cdn.sofifa.org/flags/14.png,46,66,Tranmere Rovers,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

In [5]:
import pandas as pd
data_frame = pd.read_csv('/Users/martarachwani/Desktop/data.csv')
data_frame.shape

(18207, 89)

In [6]:
data_frame.describe

<bound method NDFrame.describe of        Unnamed: 0      ID                Name  Age  \
0               0  158023            L. Messi   31
1               1   20801   Cristiano Ronaldo   33
2               2  190871           Neymar Jr   26
3               3  193080              De Gea   27
4               4  192985        K. De Bruyne   27
...           ...     ...                 ...  ...
18202       18202  238813        J. Lundstram   19
18203       18203  243165  N. Christoffersson   19
18204       18204  241638           B. Worman   16
18205       18205  246268      D. Walker-Rice   17
18206       18206  246269           G. Nugent   16

                                                Photo Nationality  \
0      https://cdn.sofifa.org/players/4/19/158023.png   Argentina
1       https://cdn.sofifa.org/players/4/19/20801.png    Portugal
2      https://cdn.sofifa.org/players/4/19/190871.png      Brazil
3      https://cdn.sofifa.org/players/4/19/193080.png       Spain
4      https://cdn.sofifa.org/players/4/19/192985.png     Belgium
...                                               ...         ...
18202  https://cdn.sofifa.org/players/4/19/238813.png     England
18203  https://cdn.sofifa.org/players/4/19/243165.png      Sweden
18204  https://cdn.sofifa.org/players/4/19/241638.png     England
18205  https://cdn.sofifa.org/players/4/19/246268.png     England
18206  https://cdn.sofifa.org/players/4/19/246269.png     England

                                      Flag  Overall  Potential  \
0      https://cdn.sofifa.org/flags/52.png       94         94
1      https://cdn.sofifa.org/flags/38.png       94         94
2      https://cdn.sofifa.org/flags/54.png       92         93
3      https://cdn.sofifa.org/flags/45.png       91         93
4       https://cdn.sofifa.org/flags/7.png       91         92
...                                    ...      ...        ...
18202  https://cdn.sofifa.org/flags/14.png       47         65
18203  https://cdn.sofifa.org/flags/46.png       47         63
18204  https://cdn.sofifa.org/flags/14.png       47         67
18205  https://cdn.sofifa.org/flags/14.png       47         66
18206  https://cdn.sofifa.org/flags/14.png       46         66

                      Club  ... Composure Marking StandingTackle  \
0             FC Barcelona  ...      96.0    33.0           28.0
1                 Juventus  ...      95.0    28.0           31.0
2      Paris Saint-Germain  ...      94.0    27.0           24.0
3        Manchester United  ...      68.0    15.0           21.0
4          Manchester City  ...      88.0    68.0           58.0
...                    ...  ...       ...     ...            ...
18202      Crewe Alexandra  ...      45.0    40.0           48.0
18203       Trelleborgs FF  ...      42.0    22.0           15.0
18204     Cambridge United  ...      41.0    32.0           13.0
18205      Tranmere Rovers  ...      46.0    20.0           25.0
18206      Tranmere Rovers  ...      43.0    40.0           43.0

       SlidingTackle GKDiving  GKHandling  GKKicking  GKPositioning  \
0               26.0      6.0        11.0       15.0           14.0
1               23.0      7.0        11.0       15.0           14.0
2               33.0      9.0         9.0       15.0           15.0
3               13.0     90.0        85.0       87.0           88.0
4               51.0     15.0        13.0        5.0           10.0
...              ...      ...         ...        ...            ...
18202           47.0     10.0        13.0        7.0            8.0
18203           19.0     10.0         9.0        9.0            5.0
18204           11.0      6.0         5.0       10.0            6.0
18205           27.0     14.0         6.0       14.0            8.0
18206           50.0     10.0        15.0        9.0           12.0

      GKReflexes Release Clause
0            8.0        €226.5M
1           11.0        €127.1M
2           11.0        €228.1M
3           94.0        €138.6M
4           13.0        €196.4M
...          ...            ...
18202        9.0          €143K
18203       12.0          €113K
18204       13.0          €165K
18205        9.0          €143K
18206        9.0          €165K

[18207 rows x 89 columns]>

In [7]:
data_frame.describe ()

,Unnamed: 0,ID,Age,Overall,Potential,Special,International Reputation,Weak Foot,Skill Moves,Jersey Number,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18207.000000,18159.000000,18159.000000,18159.000000,18147.000000,...,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000
mean,9103.000000,214298.338606,25.122206,66.238699,71.307299,1597.809908,1.113222,2.947299,2.361308,19.546096,...,48.548598,58.648274,47.281623,47.697836,45.661435,16.616223,16.391596,16.232061,16.388898,16.710887
std,5256.052511,29965.244204,4.669943,6.908930,6.136496,272.586016,0.394031,0.660456,0.756164,15.947765,...,15.704053,11.436133,19.904397,21.664004,21.289135,17.695349,16.906900,16.502864,17.034669,17.955119
min,0.000000,16.000000,16.000000,46.000000,48.000000,731.000000,1.000000,1.000000,1.000000,1.000000,...,5.000000,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,4551.500000,200315.500000,21.000000,62.000000,67.000000,1457.000000,1.000000,3.000000,2.000000,8.000000,...,39.000000,51.000000,30.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,9103.000000,221759.000000,25.000000,66.000000,71.000000,1635.000000,1.000000,3.000000,2.000000,17.000000,...,49.000000,60.000000,53.000000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,13654.500000,236529.500000,28.000000,71.000000,75.000000,1787.000000,1.000000,3.000000,3.000000,26.000000,...,60.000000,67.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,18206.000000,246620.000000,45.000000,94.000000,95.000000,2346.000000,5.000000,5.000000,5.000000,99.000000,...,92.000000,96.000000,94.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

In [8]:
data_frame.values ()

TypeError: 'numpy.ndarray' object is not callable

In [9]:
data_frame.values

array([[0, 158023, 'L. Messi', ..., 14.0, 8.0, '€226.5M'],
       [1, 20801, 'Cristiano Ronaldo', ..., 14.0, 11.0, '€127.1M'],
       [2, 190871, 'Neymar Jr', ..., 15.0, 11.0, '€228.1M'],
       ...,
       [18204, 241638, 'B. Worman', ..., 6.0, 13.0, '€165K'],
       [18205, 246268, 'D. Walker-Rice', ..., 8.0, 9.0, '€143K'],
       [18206, 246269, 'G. Nugent', ..., 12.0, 9.0, '€165K']],
      dtype=object)

In [11]:
data_frame[data_Frame["Age"]> 40].head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
1120,1120,156092,J. Villar,41,https://cdn.sofifa.org/players/4/19/156092.png,Paraguay,https://cdn.sofifa.org/flags/58.png,77,77,NaN,...,55.0,13.0,13.0,14.0,75.0,75.0,74.0,78.0,77.0,NaN
4228,4228,3665,B. Nivet,41,https://cdn.sofifa.org/players/4/19/3665.png,France,https://cdn.sofifa.org/flags/18.png,71,71,ESTAC Troyes,...,82.0,58.0,56.0,43.0,11.0,7.0,8.0,14.0,7.0,NaN
4741,4741,140029,O. Pérez,45,https://cdn.sofifa.org/players/4/19/140029.png,Mexico,https://cdn.sofifa.org/flags/83.png,71,71,Pachuca,...,62.0,23.0,12.0,11.0,70.0,64.0,65.0,73.0,74.0,€272K
7225,7225,142998,C. Muñoz,41,https://cdn.sofifa.org/players/4/19/142998.png,Argentina,https://cdn.sofifa.org/flags/52.png,68,68,CD Universidad de Concepción,...,62.0,18.0,14.0,19.0,67.0,65.0,68.0,71.0,68.0,€84K
10545,10545,140183,S. Narazaki,42,https://cdn.sofifa.org/players/4/19/140183.png,Japan,https://cdn.sofifa.org/flags/163.png,65,65,Nagoya Grampus,...,45.0,27.0,24.0,22.0,64.0,63.0,62.0,67.0,63.0,€50K

In [17]:
df1 = pd.DataFrame (data_frame, columns = ['Name', 'Wage', 'Value' ])

def value_to_float(x):
    if type(x) == float or type(x) == int:
        return x
    if 'K' in x:
        if len(x) > 1:
            return float(x.replace('K', '')) * 1000
        return 1000.0
    if 'M' in x:
        if len(x) > 1:
            return float(x.replace('M', '')) * 1000000
        return 1000000.0
    if 'B' in x:
        return float(x.replace('B', '')) * 1000000000
    return 0.0
wage = df1['Wage'].replace ('[/€,]', '', regex=True).apply(value_to_float)
value = df1['Value'].replace ('[/€,]', '', regex=True).apply(value_to_float)

df1 ['Wage'] = wage
df1 ['Value'] = value
df1 ['difference'] = df1 ['Value'] - df1 ['Wage']

df1.sort_values ('difference', ascending = False)

               Name      Wage        Value   difference
2         Neymar Jr  290000.0  118500000.0  118210000.0
0          L. Messi  565000.0  110500000.0  109935000.0
4      K. De Bruyne  355000.0  102000000.0  101645000.0
5         E. Hazard  340000.0   93000000.0   92660000.0
15        P. Dybala  205000.0   89000000.0   88795000.0
...             ...       ...          ...          ...
17752   S. Phillips    1000.0          0.0      -1000.0
12192  H. Sulaimani    3000.0          0.0      -3000.0
3550    S. Nakamura    4000.0          0.0      -4000.0
4228       B. Nivet    5000.0          0.0      -5000.0
864          Hilton   18000.0          0.0     -18000.0

[18207 rows x 4 columns]

In [28]:
df1

                     Name      Wage        Value   difference
0                L. Messi  565000.0  110500000.0  109935000.0
1       Cristiano Ronaldo  405000.0   77000000.0   76595000.0
2               Neymar Jr  290000.0  118500000.0  118210000.0
3                  De Gea  260000.0   72000000.0   71740000.0
4            K. De Bruyne  355000.0  102000000.0  101645000.0
...                   ...       ...          ...          ...
18202        J. Lundstram    1000.0      60000.0      59000.0
18203  N. Christoffersson    1000.0      60000.0      59000.0
18204           B. Worman    1000.0      60000.0      59000.0
18205      D. Walker-Rice    1000.0      60000.0      59000.0
18206           G. Nugent    1000.0      60000.0      59000.0

[18207 rows x 4 columns]

In [39]:
from bokeh.plotting import figure, show
from bokeh.models import HoverTool

TOOLTIPS = HoverTool(tooltips=[
    ("index", "$index"),
    ("(Wage,Value)", "(@Wage, @Value)"),
    ("Name", "@Name")
])


p = figure(title='soccer_2019', x_axis_label='Wage', y_axis_label='Value', plot_width=700, plot_height=700, tools=[TOOLTIPS])
p.circle(x='Wage', y='Value', size=10, source=df1)
show(p)